#!/usr/bin/ruby

require 'fileutils'

exit unless File.directory?("./basis_universal/transcoder/") && Dir.entries('./basis_universal/transcoder/').include?("basisu.h")

files = ["basisu.h", "basisu_file_headers.h", "basisu_global_selector_cb.h", "basisu_global_selector_palette.h", "basisu_transcoder.cpp", "basisu_transcoder.h", "basisu_transcoder_internal.h", "basisu_transcoder_tables_astc.inc", "basisu_transcoder_tables_astc_0_255.inc", "basisu_transcoder_tables_atc_55.inc", "basisu_transcoder_tables_atc_56.inc", "basisu_transcoder_tables_bc7_m5_alpha.inc", "basisu_transcoder_tables_bc7_m5_color.inc", "basisu_transcoder_tables_dxt1_5.inc", "basisu_transcoder_tables_dxt1_6.inc", "basisu_transcoder_tables_pvrtc2_45.inc", "basisu_transcoder_tables_pvrtc2_alpha_33.inc", "basisu_transcoder_uastc.h"]

files.map! {|file| "./basis_universal/transcoder/" + file}

FileUtils.cp files, './BasisUniversalKit/basis_universal/transcoder'
#FileUtils.cp './basis_universal/transcoder/pnglibconf.h.prebuilt', './BasisUniversalKit/transcoder/pnglibconf.h'
